FROM python:3.12-slim

ENV PYTHONUNBUFFERED=1 \
    PYTHONPATH="$PYTHONPATH:/app"

WORKDIR /app

RUN useradd -m appuser

COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

USER appuser

COPY --chown=appuser:appuser . .

EXPOSE 8501

CMD ["streamlit", "run", "frontend/app.py", "--server.address=0.0.0.0"]
